server.port=8081
spring.application.name=product-service

spring.datasource.url=jdbc:postgresql://localhost:2677/dev_authentication_db
spring.datasource.username=postgres
spring.datasource.password=BBU@2026
spring.datasource.driver-class-name=org.postgresql.Driver

# Optional: Hibernate/JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
